### PR TITLE
Quantum blockchains

### PR DESCRIPTION
**Pull request by zedleppelin74**
The `generateRandomMnemonicQBCK` method makes use of our fork of the bip39 module. The module fetches 128-bit entropy from our Quantum Random Number Generator and combines it with the entropy obtained by the random-binary module. The entropies are merged by a bitwise XOR to ensure that the final entropy is not known by anyone while keeping high randomness provided by our QRNG.

### CODE REVIEW

**Comment by mcmire** [comment]
Hi @zedleppelin74, it appears you've changed the package name. Did you mean to fork this repo first?

**Comment by zedleppelin74** [comment]
Hi @mcmire, I changed the package name so that I could test it with the Metamask fork I'm currently working on. I changed it back now.

**Comment by mcmire** [comment]
Hi again @zedleppelin74, I looked at your fork of `bip39` and it appears that in `getQRNGEntropy` [you are making an HTTP request to your own server](https://github.com/Quantum-Blockchains/bip39/blob/0e863d5d150a329d978bfe2b54035ea1e0868cf3/src/index.js#L55). This isn't something we'd want in MetaMask and for this reason we won't be able to accept this change.

You can still accomplish what you want, however. I would suggest these steps:

* Fork this package and add your desired changes to the fork. Publish this package.
* Fork our [`eth-keyring-controller` package](https://github.com/MetaMask/KeyringController) and update the [import for `eth-hd-keyring`](https://github.com/MetaMask/KeyringController/blob/e797bdf51b651dd8308e4535fdcb5896f1025073/index.js#L9) to use your fork. Publish this package.
* Update the [import for `eth-keyring-controller`](https://github.com/MetaMask/metamask-extension/blob/216f76646ed39d2f10e2a3d710a2f29a607c756d/app/scripts/metamask-controller.js#L11) in your fork of MetaMask to use your fork.

Hope that helps, and let me know if there are any questions.

**Comment by Mrtenz** [comment]
I think this can be closed now. We can re-open otherwise!

**Pull request closed without merging**
